### ISSUE TITLE
关于页面转场效果

### ISSUE THREAD

**Issue by hjs0512** [n7best/react-weui#3]
请问如果想用回默认的页面转场效果该修改哪里？

**Comment by cncolder** [comment]
你是说自带的 CSS Transition 吗? 如果是的话, 可以参考 [http://facebook.github.io/react/docs/animation.html](http://facebook.github.io/react/docs/animation.html)

**Comment by n7best** [comment]
@hjs0512 weui本身是不带router和转页效果的，类似效果你可以按自己喜好修改。 官方demo的效果你可以使用官方的[slidein](https://github.com/weui/weui/blob/master/src/example/example.less#L179-203)

**Comment by n7best** [comment]
@hjs0512  bc6dc125ccce3899de2dc4b4ea029964ba2066de 现在Page组件加入两个属性 transition和transitionTime 默认为官方效果的slideIn和.2s，效果可以选用animated.css的效果. 可以的话close这个issue
