### ISSUE TITLE
那些按钮没有点击的效果

### ISSUE THREAD

**Issue by esseak** [n7best/react-weui#5]
demo里按钮没有点击的效果，感觉冷冰冰的。正准备用 感谢作者。

**Comment by n7best** [comment]
@esseak 嗯 这两天给他们添加点东西 主要还在先完善文档 之后就会添加 谢谢建议

**Comment by esseak** [comment]
好像是ios9的问题 不确定 xcode里ios8的模拟器一直下不下来。android手机上正常

**Comment by n7best** [comment]
嗯 刚测试了下ios9 和9.2 是一个bug我测试一下

**Comment by esseak** [comment]
麻烦作者您有时间修复一下，无奈本人前端能力太弱，react更是新手，3个小时了 依然找不到解决方案

**Comment by n7best** [comment]
@esseak 给index.html的body添加 ontouchstart="" 像下面这样
```
<body style="background-color: #FBF9FE;" ontouchstart="">
  <div id="main"></div>
  <script src="bundle.js"></script>
</body>
```
会在下一个版本更新patch

**Comment by esseak** [comment]
好使！感谢 ：D
